!/bin/sh

#PBS -j oe
#PBS -o /home/lt912/sa_ea/stages/run_ea/stages/run_ea/run_outputs/oe.input6
#PBS -q pqkjelfs
#PBS -l walltime=120:00:00
#PBS -l select=1:ncpus=20:mem=100gb

module load singularity

LD_PRELOAD=""
RUN_SCRIPT=/home/lt912/sa_ea/stages/run_ea/stages/run_ea/run_ea.bash
INPUT_FILE=/home/lt912/sa_ea/stages/run_ea/stages/run_ea/create_image/input6/input6.py
singularity exec /home/lt912/singularity_images/run_ea.sif "$RUN_SCRIPT" "$INPUT_FILE"
mv stk_ea_runs/0/output.tgz /home/lt912/sa_ea/stages/run_ea/stages/run_ea/run_outputs/input6.tar.gz
