#!/bin/sh

#PBS -j oe
#PBS -o /home/lt912/sa_ea/stages/run_ea/stages/run_ea/run_outputs/oe.input5
#PBS -q pqkjelfs
#PBS -lwalltime=24:00:00
#PBS -lselect=1:ncpus=20:mem=100gb

module load singularity

LD_PRELOAD=""
RUN_SCRIPT=/home/lt912/sa_ea/stages/run_ea/stages/run_ea/run_ea.bash
INPUT_FILE=/home/lt912/sa_ea/stages/run_ea/stages/run_ea/create_image/input5/input5.py
cp "$RUN_SCRIPT" "$PWD"
singularity exec /home/lt912/singularity_images/run_ea.sif "$PWD"/run_ea.bash "$INPUT_FILE"
mv stk_ea_runs/0/output.tgz /home/lt912/sa_ea/stages/run_ea/stages/run_ea/run_outputs/input5.tar.gz
